### ISSUE TITLE
Support for parallel API function calls

### ISSUE THREAD

**Issue by JerryI** [KirillBelovTest/AILink#1]
Currently it somewhat ignores the second call. It principle there is a workaround solution - setting in the system prompt
```
Call API Functions (tool) 1 per time. Do not use parallel calls of tools.
```

**Comment by KirillBelovTest** [comment]
ОМАГАД! Оказывается тут был ишуй аж с ИЮНЯ! Кароч сделал поддержку, пасибачки!

**Comment by KirillBelovTest** [comment]
Done
